package link.infra.mkwiipresence;

import link.infra.mkwiipresence.WiimmMessages.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class MKWiiPresence {
	public class PresenceSettings {
		
	}
	
	public static void main(String[] args) {
		System.out.println("hi");
	}
	
	public static void processResponse(String json) {
		WiimmMessage[] messages = WiimmMessages.deserialize("[{\n" + 
				"    \"type\": \"room\",\n" + 
				"    \"room_id\": 499734,\n" + 
				"    \"room_name\": \"KF34\",\n" + 
				"    \"game_id4\": \"RMCJ\",\n" + 
				"    \"is_mkw\": 1,\n" + 
				"    \"ol_status\": 373,\n" + 
				"    \"ol_status_x\": \"o-G-wAR-h----\",\n" + 
				"    \"room_start\": 1518472562,\n" + 
				"    \"race_start\": 1518475418,\n" + 
				"    \"n_races\": 11}]");
		
		for (int i = 0; i < messages.length; i++) {
			if (messages[i] instanceof WiimmRoom) {
				PresenceUpdater.update(new PresenceMessage((WiimmRoom) messages[i]));
			}
		}
	}
}
